#!/usr/bin/env python3
import os
from interbotix_xs_modules.arm import InterbotixManipulatorXS
import numpy as np


def main():
    bot = InterbotixManipulatorXS("vx300s", "arm", gripper_name=None)
    bot.arm.go_to_sleep_pose()
    os.system("rosservice call /vx300s/torque_enable group arm false")


if __name__ == '__main__':
    main()